### COMANDOS DDL ###

SHOW DATABASES;
CREATE DATABASE IF NOT EXISTS pit_com_prof;
# Seleciona o BD a ser trabalhado
USE pit_com_prof;
# Cria uma tabela
CREATE TABLE IF NOT EXISTS CURSOS (
	ID INT AUTO_INCREMENT,
    NOME VARCHAR(20) UNIQUE NOT NULL,
    CARGA_HORARIA INT  NOT NULL,
    SALA VARCHAR(3),
    PERIODO INT,
    PRIMARY KEY(ID)
) DEFAULT CHARSET=UTF8;
# Adiciona uma coluna a tabela
ALTER TABLE CURSOS ADD COLUMN CIDADE VARCHAR(20) DEFAULT "Uberländia";
SHOW TABLES;
DESCRIBE CURSOS;
#Exclui uma coluna da tabela
ALTER TABLE CURSOS DROP ANO;
DESCRIBE CURSOS;
# Altera uma coluna da tabela.
ALTER TABLE CURSOS MODIFY COLUMN NOME VARCHAR(50) UNIQUE NOT NULL;
DESCRIBE CURSOS;
# Altera o nome de uma coluna da tabela.
ALTER TABLE CURSOS CHANGE CARGA_HORARIA C_HORARIO INT NOT NULL;
DESCRIBE CURSOS;
# Exclui a tabela
DROP TABLE IF EXISTS CURSOS;
# Erro pois não existe a tabela
DESCRIBE CURSOS;