algoritmo "semnome"
// Função :
// Autor :
// Data : 05/04/2022
// Seção de Declarações 
var
valor1:real
valor2:real
valor3:real
valor4:real
soma:real
inicio
Escreva("Digite o primeiro valor: ")
Leia(valor1)
Escreva("Digite o segundo valor: ")
Leia(valor2)
Escreva("Digite o terceiro valor: ")
Leia(valor3)
Escreva("Digite o quarto valor: ")
Leia(valor4)

soma <- valor1 + valor2 + valor3 + valor4

Escreva("A média dos valores é: ", soma/4)
fimalgoritmo
