algoritmo "semnome"
// Função :
// Autor :
// Data : 05/04/2022
// Seção de Declarações 
var
comprimento:real
largura:real
altura:real
volume:real
inicio
Escreva("Digite o comprimento da caixa: ")
Leia(comprimento)
Escreva("Digite a largura da caixa: ")
Leia(largura)
Escreva("Digite a altura da caixa: ")
Leia(altura)

volume<-comprimento * altura * largura
Escreva("O volume da caixa é: ", volume)
fimalgoritmo
